[2025-05-04T06:24:16.467+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: csv_to_json.convert_to_json manual__2025-05-04T06:24:12.386128+00:00 [queued]>
[2025-05-04T06:24:16.472+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: csv_to_json.convert_to_json manual__2025-05-04T06:24:12.386128+00:00 [queued]>
[2025-05-04T06:24:16.472+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-05-04T06:24:16.472+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-05-04T06:24:16.472+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-05-04T06:24:16.480+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): convert_to_json> on 2025-05-04 06:24:12.386128+00:00
[2025-05-04T06:24:16.492+0000] {standard_task_runner.py:52} INFO - Started process 260 to run task
[2025-05-04T06:24:16.494+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_to_json', 'convert_to_json', 'manual__2025-05-04T06:24:12.386128+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_json.py', '--cfg-path', '/tmp/tmpm2esb6nu', '--error-file', '/tmp/tmpmv5vwm8b']
[2025-05-04T06:24:16.495+0000] {standard_task_runner.py:80} INFO - Job 13: Subtask convert_to_json
[2025-05-04T06:24:16.533+0000] {task_command.py:371} INFO - Running <TaskInstance: csv_to_json.convert_to_json manual__2025-05-04T06:24:12.386128+00:00 [running]> on host d314c6c904e1
[2025-05-04T06:24:16.581+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_to_json
AIRFLOW_CTX_TASK_ID=convert_to_json
AIRFLOW_CTX_EXECUTION_DATE=2025-05-04T06:24:12.386128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-04T06:24:12.386128+00:00
[2025-05-04T06:24:16.592+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_to_json.py", line 34, in convertToJson
    index=False
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2571, in to_json
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 94, in to_json
    "'index=False' is only valid when 'orient' is 'split' or 'table'"
ValueError: 'index=False' is only valid when 'orient' is 'split' or 'table'
[2025-05-04T06:24:16.606+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=csv_to_json, task_id=convert_to_json, execution_date=20250504T062412, start_date=20250504T062416, end_date=20250504T062416
[2025-05-04T06:24:16.616+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 13 for task convert_to_json ('index=False' is only valid when 'orient' is 'split' or 'table'; 260)
[2025-05-04T06:24:16.636+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-05-04T06:24:16.667+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
